# cgiturl
all: zgiturl

#cgiturl:
#	@echo Testing with cgiturl backend...
#	@GITURL_TOOL="../cgiturl/cgiturl" ./short.bats
#	@echo

zgiturl:
	@echo Testing with zgiturl backend...
	@GITURL_TOOL="../giturl/zgiturl" ./short.bats
	@echo

short:
#	@echo Testing with cgiturl backend...
#	@GITURL_TOOL="../cgiturl/cgiturl" ./short.bats
#	@echo
	@echo Testing with zgiturl backend...
	@GITURL_TOOL="../giturl/zgiturl" ./short.bats

# cgiturl
.PHONY: all zgiturl short
