#!/bin/bash
# -*- mode: shell-script -*-
# vim:ft=sh

GITURL_TOOL=${GITURL_TOOL#"${GITURL_TOOL%%[![:space:]]*}"} # leading white space
GITURL_TOOL=${GITURL_TOOL%"${GITURL_TOOL##*[![:space:]]}"} # trailing white space

#
# Functions
#

show_help() {
    echo "git url [-h] [-q] [-r <revision>] [gitu://...]"
    echo ""
    echo "-h    show this message"
    echo "-q    quiet mode (less output)"
    echo "-n    no ansi colors"
    echo "-r    use custom revision like 'master' or '3a7abce' instead of fetching it from repository"
    echo ""
    echo "If gitu://... is passed, it will be decoded."
}

#
# Parse options
#

OPTIND=1
HELP=""
QUIET=""
NOANSI=""
REVISION=""

while getopts "hqnr:" opt; do
    case "$opt" in
        \?)
            echo "Error: incorrect option, aborting."
            echo ""
            show_help
            exit 1
            ;;
        h)
            show_help
            exit 0
            ;;
        q)  QUIET="-q"
            ;;
        n)  NOANSI="-n"
            ;;
        r)  REVISION="$OPTARG"
            ;;
    esac
done

shift $(( OPTIND-1 ))

[[ "$1" = "--" ]] && shift

