name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install zsh bats -yq

    - name: Prepare
      run: |
        git submodule update --init --recursive
        make

    - name: Run test
      run: make test

