name: Test Git-URL

on:
  push:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        token: ${{ secrets.GITHUB_TOKEN }}
        submodules: 'recursive'

    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install zsh bats -yq

    - name: Install tools
      run: |
        make clean
        make all
        sudo make install

    - name: Run test
      run: |
        ./git-url
        ./git-guclone
        make test
