name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test install
      run: make install
